language: node_js
node_js:
  - node

sudo: false # faster builds

cache:
  directories:
    - sysconfcpus
    - node_modules

notifications:
  email: false

before_install:
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install -g yarn
  - make install
  - npm install elm-format-download
  - ./node_modules/.bin/elm-format-download

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make build
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make test
  - ./node_modules/elm-format-download/downloads/elm-format --validate src tests
